---
servers:
  - name: TP1
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet1, Ethernet1 ]
        switches: [ CAGEA-LEAF-1A, CAGEA-LEAF-1B ]
        vlans: 3030
        mode: trunk
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel TP1
          mode: active
  - name: TP2
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet1, Ethernet1 ]
        switches: [ CAGEA-LEAF-2A, CAGEA-LEAF-2B ]
        vlans: 3030
        mode: trunk
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel host3
          mode: active