---
port_profiles:
  - profile: ESXi
    mode: trunk
    vlans: 3030, 3040, 55, 56
    spanning_tree_portfast: edge
    port_channel:
      mode: active

network_ports:
  - switches: [CAGEA-LEAF-1A, CAGEA-LEAF-1A]
    switch_ports: [Ethernet1, Ethernet1]
    profile: ESXi

servers:
  - name: TP2
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet1, Ethernet1 ]
        switches: [ CAGEA-LEAF-2A, CAGEA-LEAF-2B ]
        vlans: 3030, 3040, 55, 56
        mode: trunk
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel host3
          mode: active

  - name: Firewall
    adapters:
      - endpoint_ports: [Ethernet1, Ethernet2]
        switch_ports: [Ethernet47, Ethernet47]
        switches: [CAGEA-BORDER-1A, CAGEA-BORDER-1B]
        vlans: 3030, 3040, 55
        mode: trunk
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel firewall
          mode: active 